### PR TITLE
chore: use updatecli to keep the base image up to date

### PR DESCRIPTION
**Pull request by garethjevans**
### What this PR does / why we need it

This tool introduces a tool called [updatecli](https://www.updatecli.io/) that can be used to automatically bump an image digest inside a `.ko.yaml` file.  This will allow us to produce repeatable builds

The cron is set to trigger every hour (or on demand)

You can test this locally with:

```
act workflow_dispatch -j update
```

### CODE REVIEW

**Review by rashedkvm — APPROVED** [review]
This is great. Looks good to me. 

Few comments:

1. Current implementation targets `.ko.yaml` in `main`
2. Does this process extends to a branch? A typical use case will be when creating a patch release from a branch other than `main`.

**Comment by garethjevans** [comment]
> This is great. Looks good to me.
> 
> Few comments:
> 
> 1. Current implementation targets `.ko.yaml` in `main`
> 2. Does this process extends to a branch? A typical use case will be when creating a patch release from a branch other than `main`.

There are ways to trigger this against a branch too - https://stackoverflow.com/questions/58798886/github-actions-schedule-operation-on-branch

**Comment by garethjevans** [comment]
Having said that, if the branch was created as a "release branch", we probably don't want to be updating the image its built on top of unless there is a strong reason to

**Comment by katmutua** [comment]
Thanks @garethjevans  :shipit:

**Review by katmutua — APPROVED** [review]

**Comment by rashedkvm** [comment]
> Having said that, if the branch was created as a "release branch", we probably don't want to be updating the image its built on top of unless there is a strong reason to

I concur!

**Pull request merged**
